### PR TITLE
Fix typo in doc code

### PR DESCRIPTION
**Pull request by pfeodrippe**
I've tried to copy this snipped and my IDE started to complain about an unclosed string.

Thanks for this awesome project BTW \o/

### CODE REVIEW

**Comment by plexus** [comment]
Oohhh good catch! Thank you!

**Comment by pfeodrippe** [comment]
> Oohhh good catch! Thank you!

NP, let me know what else you need so we can merge this o/

**Comment by plexus** [comment]
Oops I guess I forgot to actually press the button :)

**Comment by plexus** [comment]
Released in [v1.10.94](https://github.com/lambdaisland/ornament/releases/tag/v1.10.94)

```clj
[com.lambdaisland/ornament "1.10.94"]                 ;; deps.edn
{com.lambdaisland/ornament {:mvn/version "1.10.94"}}  ;; project.clj
```

**Pull request merged**
