### PR TITLE
[WIP] bump girouette

### PR DESCRIPTION
**Pull request by oxalorg**
This PR updates griouette to v0.0.10 while still mainting backward compat

i.e. ornament will still be using Tailwind v2 bindings in girouette instead of using the updated Tailwind v3 functions.

In v0.0.8 girouette made some breaking changes. Look #18 for more info

### CODE REVIEW

**Comment by plexus** [comment]
Seems we don't need much to be able to let the user opt-in to v3
- they can already set the different tokens (fonts, colors, components)
- the preflight can be handled outside of ornament, it's just a convenience that we include it
- the classname function would have to become configurable, that's not the case yet

Can we make that classname function configurable? And then document in the readme what it would look like if someone wants to opt-in to v3?

**Comment by GetBitOutdoors** [comment]
Having trouble getting bumps working:
https://github.com/lambdaisland/ornament/issues/18#issuecomment-1242791727

**Comment by GetBitOutdoors** [comment]
There is a bug (from formatting?):
`(:require)` terminates early
https://github.com/lambdaisland/ornament/blob/a0f96cdb6f74d2bf9a26117582bcf41e28ba9167/src/lambdaisland/ornament.cljc#L4

**Comment by plexus** [comment]
Thanks @GetBitOutdoors, that should be fixed now.

**Comment by plexus** [comment]
2022-09-19_105139_firefox-nightly

One failing test.

**Comment by daaku** [comment]
Any chance of getting this into a release? Being able to use the current version of girouette would be nice.

**Comment by plexus** [comment]
Released in

```
[com.lambdaisland/ornament "0.7.77"]
{com.lambdaisland/ornament {:mvn/version "0.7.77"}}
```

**Pull request merged**
